# Generated by Django 4.2.14 on 2024-07-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('status', models.IntegerField(default=0)),
                ('personal', models.BooleanField(default=False, null=True)),
                ('settings', models.JSONField(default={}, null=True)),
                ('created_at', models.BigIntegerField(null=True)),
                ('updated_at', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField()),
                ('profile', models.JSONField(default={})),
                ('status', models.IntegerField(default=0)),
                ('setttings', models.JSONField(default={}, null=True)),
                ('created_at', models.BigIntegerField(null=True)),
                ('updated_at', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField(null=True)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('settings', models.JSONField(default={}, null=True)),
                ('created_at', models.BigIntegerField(null=True)),
                ('updated_at', models.BigIntegerField(null=True)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.organisation')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
        ),
    ]
